version: '3.4'
services:
  php-apache:
    container_name: evertec
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_XDEBUG_HOST: '${IP_LOCAL}'
        APP_XDEBUG_PORT: '${PORT_DEBUG}'
    ports:
      - "${PORT_LOCAL}:80"
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
    networks:
      - evertec
networks:
  evertec:
    external: true